"use client";

import * as React from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ShieldCheck, KeyRound, AlertCircle, ArrowRight, Loader2, LifeBuoy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import Link from "next/link";

function AdminMfaVerifyContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const redirectTo = searchParams.get("redirectTo") || "/admin/dashboard";

  const [totpCode, setTotpCode] = React.useState("");
  const [recoveryCode, setRecoveryCode] = React.useState("");
  const [useRecoveryMode, setUseRecoveryMode] = React.useState(false);
  const [factorId, setFactorId] = React.useState<string | null>(null);
  const [isLoading, setIsLoading] = React.useState(false);
  const [errorMsg, setErrorMsg] = React.useState<string | null>(null);

  React.useEffect(() => {
    async function loadMfaStatus() {
      try {
        const res = await fetch("/api/admin/mfa/status");
        if (res.ok) {
          const data = await res.json();
          if (data.factorId) {
            setFactorId(data.factorId);
          }
        }
      } catch (err) {
        console.error("Failed to load factor ID:", err);
      }
    }
    loadMfaStatus();
  }, []);

  async function handleVerify(e: React.FormEvent) {
    e.preventDefault();
    if (!useRecoveryMode && (!totpCode || totpCode.length !== 6)) {
      setErrorMsg("Please enter the 6-digit code from your authenticator app.");
      return;
    }

    if (useRecoveryMode && !recoveryCode.trim()) {
      setErrorMsg("Please enter your backup recovery code.");
      return;
    }

    setIsLoading(true);
    setErrorMsg(null);

    try {
      const payload = useRecoveryMode
        ? { recoveryCode: recoveryCode.trim() }
        : { factorId, code: totpCode.trim() };

      const res = await fetch("/api/admin/mfa/verify", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      const data = await res.json();

      if (!res.ok) {
        setErrorMsg(data.message || data.error || "MFA verification failed.");
        setIsLoading(false);
        return;
      }

      // Elevated session -> redirect to original destination
      router.replace(redirectTo);
    } catch (err) {
      console.error("Verification error:", err);
      setErrorMsg("An unexpected network error occurred.");
      setIsLoading(false);
    }
  }

  return (
    <div className="flex min-h-screen w-full items-center justify-center bg-zinc-950 px-4 py-12 text-zinc-100">
      <div className="relative w-full max-w-md space-y-6 rounded-3xl border border-zinc-800/80 bg-zinc-900/90 p-8 shadow-2xl backdrop-blur-xl">
        <div className="flex flex-col items-center text-center space-y-2">
          <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-tr from-heat-600 via-heat-500 to-amber-400 text-white shadow-xl shadow-heat-500/25">
            <ShieldCheck className="h-9 w-9" />
          </div>
          <h1 className="text-2xl font-bold tracking-tight text-white">Two-Factor Authentication</h1>
          <p className="text-xs text-zinc-400">
            {useRecoveryMode
              ? "Enter one of your single-use backup recovery codes."
              : "Enter the 6-digit security code generated by your authenticator app."}
          </p>
        </div>

        {errorMsg && (
          <div className="flex items-start gap-2.5 rounded-2xl border border-red-500/30 bg-red-500/10 p-3.5 text-xs text-red-300">
            <AlertCircle className="h-4 w-4 shrink-0 text-red-400 mt-0.5" />
            <p>{errorMsg}</p>
          </div>
        )}

        <form onSubmit={handleVerify} className="space-y-4">
          {!useRecoveryMode ? (
            <div className="space-y-1.5">
              <label className="text-xs font-semibold uppercase tracking-wider text-zinc-400">
                Security Code
              </label>
              <Input
                type="text"
                placeholder="000000"
                maxLength={6}
                value={totpCode}
                onChange={(e) => setTotpCode(e.target.value.replace(/\D/g, ""))}
                className="text-center font-mono text-2xl tracking-widest bg-zinc-950 border-zinc-800 text-white focus-visible:ring-heat-500"
                required
                autoFocus
              />
            </div>
          ) : (
            <div className="space-y-1.5">
              <label className="text-xs font-semibold uppercase tracking-wider text-zinc-400">
                Backup Recovery Code
              </label>
              <Input
                type="text"
                placeholder="XXXX-XXXX-XXXX"
                value={recoveryCode}
                onChange={(e) => setRecoveryCode(e.target.value.toUpperCase())}
                className="text-center font-mono text-base tracking-wider bg-zinc-950 border-zinc-800 text-amber-400 focus-visible:ring-heat-500"
                required
                autoFocus
              />
            </div>
          )}

          <Button
            type="submit"
            variant="heat"
            size="lg"
            className="w-full font-medium"
            disabled={isLoading || (!useRecoveryMode && totpCode.length !== 6)}
          >
            {isLoading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Verifying Code...
              </>
            ) : (
              <>
                Verify & Continue
                <ArrowRight className="ml-2 h-4 w-4" />
              </>
            )}
          </Button>
        </form>

        <div className="flex flex-col items-center gap-3 border-t border-zinc-800/80 pt-6 text-xs text-zinc-500">
          <button
            type="button"
            onClick={() => {
              setUseRecoveryMode(!useRecoveryMode);
              setErrorMsg(null);
            }}
            className="flex items-center gap-1.5 text-heat-400 hover:text-heat-300 transition-colors"
          >
            <LifeBuoy className="h-3.5 w-3.5" />
            {useRecoveryMode ? "Use Authenticator App Instead" : "Lost access? Use a Recovery Code"}
          </button>

          <Link href="/admin/login" className="hover:text-zinc-300 transition-colors">
            Return to Admin Login
          </Link>
        </div>
      </div>
    </div>
  );
}

export default function AdminMfaVerifyPage() {
  return (
    <React.Suspense
      fallback={
        <div className="flex min-h-screen w-full items-center justify-center bg-zinc-950 text-white">
          <Loader2 className="h-8 w-8 animate-spin text-heat-500" />
        </div>
      }
    >
      <AdminMfaVerifyContent />
    </React.Suspense>
  );
}
